### ISSUE TITLE
Need help with maintenance?

### ISSUE THREAD

**Issue by iMacTia** [nicolasblanco/rails_param#40]
Hi @nicolasblanco,

just touching base with you regarding maintenance for `rails_param`.
I absolutely love this gem and I've been using for 2-3 years now, but I notice it's not easy for you to follow Issue/PRs.
As the main [Faraday](https://github.com/lostisland/faraday) maintainer, I absolutely understand you probably have a lot of things to do and you're alone managing the gem.

I'm here to offer my help as a co-maintainer. I'm happy to review PR, triage Issue and even merge PR if you're OK with it. I'm also happy to leave release permissions to you only if you prefer to keep control of the release process.

I can see a lot of great ideas just waiting to be reviewed/merged but hanging forever, so rather than complaining I decided to offer my help.

Let me know your thoughts.

**Comment by nicolasblanco** [comment]
Hey there @iMacTia,

sorry it took me a while to see your message. I've just set you as a collaborator.
Have fun 😄.

**Comment by nicolasblanco** [comment]
@iMacTia : I think to add you as collaborator on rubygems I need the address email you use, right:
https://guides.rubygems.org/command-reference/#gem-owner
?

**Comment by iMacTia** [comment]
@nicolasblanco that's right, here is my profile where you should see my email: https://rubygems.org/profiles/iMacTia

Your opinion will still be very much appreciated, so in case I have questions for you regarding important decisions, what's your favourite communication channel for me to reach you?

**Comment by nicolasblanco** [comment]
@iMacTia : I've just added you on rubygems for this gem. You should be able to push new releases.

Also my main opinion on this gem is that originally it was taking code from the sinatra lib.

The issue is that Rails already contains ActiveModel and a validation system. We don't need many validations systems, ActiveModel is already fine.

So my idea is inside : https://github.com/nicolasblanco/rails_param/issues/2

Basically it would be maybe to dynamically create an ActiveModel class in the current Thread and validate the params against it.

The developper would be able to use the ActiveModel validators that he/she likes and the gem would not contain all the custom validations rules anymore, a great DRY.

I don't think it would be very complicated to do that. Of course it would completely break the current API, but would be perfect for a 1.0 release...

**Comment by iMacTia** [comment]
Thanks @nicolasblanco.
I agree with you, we could delegate validation to `ActiveModel` and keep only type coercion as custom logic. I'll try to explore this route and see what happens.
I'd also like to see if I can change tests to use "anonymous controllers" a new Spec feature that should make tests easier and more self-contained.

But first, I'd like to go through all the open PR/Issue and identify "quick wins", stuff that we can easily review and merge that would bring immediate value to the gem.
I'm classifying some PR/Issue with milestones (0.10.1 for quick fixes, 0.11.0 for quick features) and will probably release those 2 versions first.

Feel free to contact me directly by email if you want to discuss more
