### ISSUE TITLE
Hash type validation

### ISSUE THREAD

**Issue by mike927** [nicolasblanco/rails_param#68]
## Basic Info

* rails_param Version: 0.11.1
* Ruby Version: 3.0.1
* Rails Version: 6.1.3.1

## Issue description
It seems like Hash type validation does not work as expected. Having the following:
```ruby
       param! :receipt, Hash, required: true, blank: false do |receipt|
            receipt.param! :packageName, String, required: true, blank: false
            receipt.param! :productId, String, required: true, blank: false
            receipt.param! :purchaseToken, String, required: true, blank: false
       end
```
```ruby
        let(:request_params) do
            {
              receipt: 'some-string'
            }
        end
```

I expect to receive a `receipt` attr value as a hash with nested attributes. On the other hand, instead of wrong type error the spec passes while the key value is just a string.

Could anyone reproduce that case and confirm whether the issue exists? 

Thanks in advance.

**Comment by iMacTia** [comment]
That is strange but thanks for the details @mike927, I'm taking a look 👍

**Comment by iMacTia** [comment]
@mike927 I added this test locally and it successfully passes:

```ruby
it "will raise InvalidParameterError if the value is an invalid string" do
  allow(controller).to receive(:params).and_return({ "foo" => 'some-string' })
  expect do
    controller.param! :foo, Hash, required: true, blank: false do |receipt|
      receipt.param! :packageName, String, required: true, blank: false
      receipt.param! :productId, String, required: true, blank: false
      receipt.param! :purchaseToken, String, required: true, blank: false
    end
  end.to raise_error(RailsParam::Param::InvalidParameterError)
end
```

So unfortunately I've been unable to reproduce, the gem seems to behave as expected (raises `RailsParam::Param::InvalidParameterError` in your particular use-case.
Could you maybe insert a debug line above the first `receipt.param!` check in the block and do some debugging there to see if the code is actually called and doesn't raise an exception?
Since you're inside the test environment, there are a few things that may be happening here, for example:
* The `param!` method is not actually called, or is mocked
* The code above is actually executed and raises an exception, but this is swallowed/rescued somewhere else

**Comment by iMacTia** [comment]
@mike927 have you managed to solve or investigate this further? Any feedback might be useful for future readers 😄

**Comment by mike927** [comment]
Hi, sorry for a very long reply. Please consider a very simple case:
```ruby
  def create
    param! :receipt, Hash, required: true
  end
```

Request Body:
```json
{
    "receipt": "string"
}
```

The above example does not raise an error to me.
On the other hand, below one:

Request Body:
```json
{
    "receipt": 1
}
```
raises excepted error:
```json
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<RailsParam::InvalidParameterError: '1' is not a valid Hash>",
```

**Comment by iMacTia** [comment]
Oh, I see now! This is because of hashes coercion then 😄!
`rails_param` automatically coerce strings into hashes, so that strings like `"a:1,b:2"` become `{ a: 1, b: 2 }`.
Now, yours is a bit of a special case, as what's happening here is that `"string"` becomes `{ string: nil }`.
As you can see, this only works with strings, the check correctly fails with numbers.

We've recently discussed this in another PR (#81) and I agree it can be confusing at first, but this feature has been there since the beginning and is relied on by many users, so we can't change it lightly.

I hope this helps!

**Comment by mike927** [comment]
Thanks for explanation. Feel free to close this issue.
