### ISSUE TITLE
I want to allow arrays of nullable integer types.

### ISSUE THREAD

**Issue by kotaesaki** [nicolasblanco/rails_param#96]
Thank you very much for allowing us to use rails_param!
I have one question.

As the title says, what should I do if I receive an array that accepts null as a parameter?

```.rb
def validate_params
  param! :ids, Array, required: true do |item, id|
    item.param! id, Integer # I want to allow this to be null!
  end
end
```

Forgive my newbie question.

## Basic Info

* rails_param Version: 1.3.0
* Ruby Version: 3.0.3
* Rails Version: 7.0.3

**Comment by iMacTia** [comment]
Hi @kotaesaki, I'm not sure you can make this right now.
I'm also not entirely sure how you'd provide `nil` in the array, to be honest.
The only workaround I can think of without having to change the code, is to accept Strings rather than Integers and use a transform function.

Here is a quick stab (NOTE: this is untested):
```ruby
def validate_params
  param! :ids, Array, required: true do |item, id|
    item.param! id, String, transform: -> { |n| n == 'null' ? nil : n.to_i }
  end
end
```

**Comment by kotaesaki** [comment]
@iMacTia 
Thanks for your reply!
We know that it is inherently inappropriate to allow null in params, but a compelling situation has arisen.
I would like to try the approach you suggested.
